#!/bin/sh

# Gradle start up script for POSIX generated by Gradle.

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

# Resolve the path to this script.
APP_HOME=$(cd "${APP_BASE_NAME%/*}" 2>/dev/null && pwd -P) || exit 1

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

JAVA_EXEC="${JAVA_HOME:+$JAVA_HOME/bin/}java"

exec "$JAVA_EXEC" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
